theme: jekyll-theme-cayman
title: "Exeter Data Analytics Hub"
description: "Site for workshops organised at the University of Exeter"
baseurl: ""
markdown: kramdown
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
